src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     */
    private $surname;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $image;

    /**
     * @ORM\Column(type="string", length=10, nullable=true)
     */
    private $status;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updated_at;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isVerified = false;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getSurname(): ?string
    {
        return $this->surname;
    }

    public function setSurname(?string $surname): self
    {
        $this->surname = $surname;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(?string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(?\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }
}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Validator\Constraints\File;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\CallbackTransformer;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('email')
            //->add('roles')
            ->add('password', PasswordType::class, [
                // instead of being set onto the object directly,
                // this is read and encoded in the controller
                'mapped' => false,
                'constraints' => [
                    new NotBlank([
                        'message' => 'Please enter a password',
                    ]),
                    new Length([
                        'min' => 6,
                        'minMessage' => 'Your password should be at least {{ limit }} characters',
                        // max length allowed by Symfony for security reasons
                        'max' => 4096,
                    ]),
                ],
            ])
            ->add('name')
            ->add('surname')
            ->add('image', FileType::class, [
                'label' => 'Ev Main Image',
                'mapped' => false,
                'required' => false,
                
                'constraints' => [
                    new File([
                        'maxSize' => '1024k',
                        'mimeTypes' => [
                            'image/*',
                        ],
                        'mimeTypesMessage' => 'Please upload a valid Image File',
                    ])
                ],
            ])
        ;
    }



    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

src/Controller/Admin/UserController.php
<?php

namespace App\Controller\Admin;

use App\Entity\User;
use App\Form\UserType;
use App\Repository\UserRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

/**
 * @Route("/admin/user")
 */
class UserController extends AbstractController
{
    /**
     * @Route("/", name="admin_user_index", methods={"GET"})
     */
    public function index(UserRepository $userRepository): Response
    {
        return $this->render('admin/user/index.html.twig', [
            'users' => $userRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="admin_user_new", methods={"GET","POST"})
     */
    public function new(Request $request, UserPasswordEncoderInterface $passwordEncoder): Response
    {
        $user = new User();
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();

             //------------------Image Upload--------------//
            /** @var file $flie */
            $file = $form['image']->getData();
            if ($file) {
                $fileName = $this->generateUniqueFileName() . '.' . $file->guessExtension();


                // Move the file to the directory where brochures are stored
                try {
                    $file->move(
                        $this->getParameter('images_directory'), // in Service.yaml defined images directory
                        $fileName
                    );
                } catch (FileException $e) {
                    //..handle exception if something happens during file upload
                }
                $user->setImage($fileName);
            }
            //------------------Image Upload--------------//
            $user->setPassword(
                $passwordEncoder->encodePassword(
                    $user,
                    $form->get('password')->getData()
                )
            );
            $entityManager->persist($user);
            $entityManager->flush();

            return $this->redirectToRoute('admin_user_index');
        }

        return $this->render('admin/user/new.html.twig', [
            'user' => $user,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="admin_user_show", methods={"GET"})
     */
    public function show(User $user): Response
    {
        return $this->render('admin/user/show.html.twig', [
            'user' => $user,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="admin_user_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, User $user, UserPasswordEncoderInterface $passwordEncoder): Response
    {
        $form = $this->createForm(AdminUserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

              //------------------Image Upload--------------//
            /** @var file $flie */
            $file = $form['image']->getData();
            if ($file) {
                $fileName = $this->generateUniqueFileName() . '.' . $file->guessExtension();


                // Move the file to the directory where brochures are stored
                try {
                    $file->move(
                        $this->getParameter('images_directory'), // in Service.yaml defined images directory
                        $fileName
                    );
                } catch (FileException $e) {
                    //..handle exception if something happens during file upload
                }
                $user->setImage($fileName);
            }
            //------------------Image Upload--------------//
            $user->setPassword(
                $passwordEncoder->encodePassword(
                    $user,
                    $form->get('password')->getData()
                )
            );
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('admin_user_index');
        }

        return $this->render('admin/user/edit.html.twig', [
            'user' => $user,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="admin_user_delete", methods={"DELETE"})
     */
    public function delete(Request $request, User $user): Response
    {
        if ($this->isCsrfTokenValid('delete'.$user->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($user);
            $entityManager->flush();
        }

        return $this->redirectToRoute('admin_user_index');
    }
    /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }

}

templates/user/_delete_form.html.twig
<form method="post" action="{{ path('user_delete', {'id': user.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
    <button class="btn">Delete</button>
</form>

templates/user/comments.html.twig
{% extends 'homebase.html.twig' %}

{% block title %}{{ app.user.name }}-Comments{% endblock %}

{% block body %}
<section id="content" class="shortcode-item">
    <div class="container">
        <div class="row">
            <div class="col-xs-4 col-sm-2">

                <div class="tab-wrap">
                    <div align="center" class="media">
                            {{ include('user/usermenu.html.twig') }}

                        <!--/.media-body-->
                    </div>
                    <!--/.media-->
                </div>
                <!--/.tab-wrap-->
            </div>
            <!--/.col-sm-6-->

            <div align="center" class="col-xs-8 col-sm-10">
                <h2>My Comments</h2>
 <table class="table">
                                <thead>
                                    <tr>
                                        <th>Id</th>
                                        <th>Subject</th>
                                        <th>Comment</th>
                                        <th>Status</th>
                                        <th>Home Name</th>
                                        <th>Created_At</th>
                                        <th>Rate</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for comment in comments %}
                                    <tr>
                                        <td>{{ comment.id }}</td>
                                        <td>{{ comment.subject }}</td>
                                        <td>{{ comment.comment }}</td>
                                        <td>{{ comment.status }}</td>
                                        <td nowrap ><a href="{{ path('ev_show', {'id': comment.evid}) }}">{{ comment.title }} </a></td>
                                        <td>{{ comment.created_at}}</td>
                                        {#<td>{{ comment.updatedAt ? comment.updatedAt|date('Y-m-d H:i:s') : '' }}</td> #}
                                        <td>{{ comment.rate }}</td>
                                    </tr>
                                    {% else %}
                                    <tr>
                                        <td colspan="10">no records found</td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
            </div>
        </div>
        <!--/.row-->
    </div>
    <!--/.container-->
</section>
<!--/#content-->

{% endblock %}

templates/user/edit.html.twig
{% extends 'homebase.html.twig' %}

{% block title %}{{ app.user.name }}-Comments{% endblock %}

{% block body %}
<section id="content" class="shortcode-item">
    <div class="container">
        <div class="row">
            <div class="col-xs-4 col-sm-2">

                <div class="tab-wrap">
                    <div align="center" class="media">
                        {{ include('user/usermenu.html.twig') }}

                        <!--/.media-body-->
                    </div>
                    <!--/.media-->
                </div>
                <!--/.tab-wrap-->
            </div>
            <!--/.col-sm-6-->

            <div align="center" class="col-xs-8 col-sm-10">
                <h2>Edit My Informations</h2>
                {{ include('user/_form.html.twig', {'button_label': 'Update'}) }}

            </div>
        </div>
        <!--/.row-->
    </div>
    <!--/.container-->
</section>
<!--/#content-->

{% endblock %}

templates/user/ev.html.twig
{% extends 'homebase.html.twig' %}

{% block title %}{{ app.user.name }}-Rent-House{% endblock %}

{% block body %}
<section id="content" class="shortcode-item">
    <div class="container">
        <div class="row">
            <div class="col-xs-4 col-sm-2">

                <div class="tab-wrap">
                    <div align="center" class="media">
                        {{ include('user/usermenu.html.twig') }}

                        <!--/.media-body-->
                    </div>
                    <!--/.media-->
                </div>
                <!--/.tab-wrap-->
            </div>
            <!--/.col-sm-6-->

            <div align="center" class="col-xs-8 col-sm-10">
                <h2>Rent House</h2>
                Rent House
            </div>
        </div>
        <!--/.row-->
    </div>
    <!--/.container-->
</section>
<!--/#content-->

{% endblock %}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}User index{% endblock %}

{% block body %}
    <h1>User index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Email</th>
                <th>Roles</th>
                <th>Password</th>
                <th>Name</th>
                <th>Surname</th>
                <th>Image</th>
                <th>Status</th>
                <th>Created_at</th>
                <th>Updated_at</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for user in users %}
            <tr>
                <td>{{ user.id }}</td>
                <td>{{ user.email }}</td>
                <td>{{ user.roles ? user.roles|json_encode : '' }}</td>
                <td>{{ user.password }}</td>
                <td>{{ user.name }}</td>
                <td>{{ user.surname }}</td>
                <td>{{ user.image }}</td>
                <td>{{ user.status }}</td>
                <td>{{ user.createdAt ? user.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ user.updatedAt ? user.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('user_show', {'id': user.id}) }}">show</a>
                    <a href="{{ path('user_edit', {'id': user.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="11">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('user_new') }}">Create new</a>
{% endblock %}

templates/user/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New User{% endblock %}

{% block body %}
    <h1>Create new User</h1>

    {{ include('user/_form.html.twig') }}

    <a href="{{ path('user_index') }}">back to list</a>
{% endblock %}

templates/user/newreservation.html.twig
{% extends 'homebase.html.twig' %}

{% block title %}{{ app.user.name }}-Rents{% endblock %}

{% block body %}

<section id="content" class="shortcode-item">
    <div class="container">
        <div class="row">
            <div class="col-xs-4 col-sm-2">

                <div class="tab-wrap">
                    <div align="center" class="media">
                        {{ include('user/usermenu.html.twig') }}

                    </div>
                    <!--/.media-->
                </div>
                <!--/.tab-wrap-->
            </div>
            <!--/.col-sm-6-->

            <div align="center" class="col-xs-8 col-sm-10">
                <h2>Rent</h2>
                <hr>
                <h4>Home: {{ ev.title }}</h4>
<table align="center" class="col-xs-6 col-sm-6">
                <div class="price-box">
                    <span>Price:{{ev.price}}₺</span>
                </div>
</table>
                <hr>
                {{ include('messages.html.twig') }}

                <div class="row contact-wrap">
                    <div class="status alert alert-success" style="display: none"></div>
                    <form name="reservation" method="post" class="contact-form" role="form">
                        <div class="col-sm-5 col-sm-offset-1" id="reservation">
                            <div class="form-group">
                                <label for="reservation_name">Name *</label>
                                <input type="text" id="reservation_name" name="reservation[name]" value="{{ app.user.name }}" class="form-control"
                                    required="required">
                            </div>
                            <div class="form-group">
                                <label for="reservation_surname">Sruname *</label>
                                <input type="text" id="reservation_name" name="reservation[surname]" value="{{ app.user.surname }}" class="form-control"
                                    required="required">
                            </div>
                            <div class="form-group">
                                <label for="reservation_email">Email *</label>
                                <input type="email" id="reservation_email" name="reservation[email]" value="{{ app.user.email }}" class="form-control"
                                    required="required">
                            </div>
                            <div class="form-group">
                                <label for="reservation_subject">Phone *</label>
                                <input type="text" id="reservation_phone" name="reservation[phone]" class="form-control"
                                    required="required">
                            </div>
                        </div>
                        <div class="col-sm-5">
                            <div class="form-group">
                                <label for="reservation_message">Message *</label>
                                <textarea id="reservation_message" name="reservation[message]" required="required"
                                    class="form-control" rows="8"></textarea>
                            </div>
                            <div class="form-group">
                            **************Credit Card Informations ********************
                                <input type="hidden" name="token" value="{{ csrf_token('form-reservation') }}" />
                                <button type="submit" class="btn btn-primary btn-lg">Rent</button>
                            </div>
                        </div>
                    </form>
                    <!--/.row-->
                </div>
            </div>
        </div>
        <!--/.row-->
    </div>
    <!--/.container-->
</section>
<!--/#content-->

{% endblock %}

templates/user/renthouse.html.twig
{% extends 'homebase.html.twig' %}

{% block title %}{{ app.user.name }}-Rent-House{% endblock %}

{% block body %}
<section id="content" class="shortcode-item">
    <div class="container">
        <div class="row">
            <div class="col-xs-4 col-sm-2">

                <div class="tab-wrap">
                    <div align="center" class="media">
                        {{ include('user/usermenu.html.twig') }}

                        <!--/.media-body-->
                    </div>
                    <!--/.media-->
                </div>
                <!--/.tab-wrap-->
            </div>
            <!--/.col-sm-6-->

            <div align="center" class="col-xs-8 col-sm-10">
                <h2>Rent House</h2>
                Rent House
            </div>
        </div>
        <!--/.row-->
    </div>
    <!--/.container-->
</section>
<!--/#content-->

{% endblock %}

templates/user/reservation_show.html.twig
{% extends 'homebase.html.twig' %}

{% block title %}{{ app.user.name }}-Reservations{% endblock %}

{% block body %}
<section id="content" class="shortcode-item">
    <div class="container">
        <div class="row">
            <div class="col-xs-4 col-sm-2">

                <div class="tab-wrap">
                    <div align="center" class="media">
                        {{ include('user/usermenu.html.twig') }}

                        <!--/.media-body-->
                    </div>
                    <!--/.media-->
                </div>
                <!--/.tab-wrap-->
            </div>
            <!--/.col-sm-6-->

            <div align="center" class="col-xs-8 col-sm-10">
                <h2>My Rents</h2>

                <table class="table">

                        <tr>
                            <th>Home</th>
                            <td><a href="{{ path('ev_show', {'id': reservation[0].evid}) }}">{{ reservation[0].hname }}</a></td>
                        </tr>
                        <tr>
                            <th>Name</th>
                            <td><a href="{{ path('user_show', {'id': reservation[0].userid}) }}">{{ reservation[0].name }}</a></td>
                        </tr>
                            <th>Surname</th>
                            <td>{{ reservation[0].surname }}</td>
                        <tr>
                            <th>Email</th>
                            <td>{{ reservation[0].email }}</td>
                        </tr>
                        <tr>
                            <th>Phone</th>
                            <td>{{ reservation[0].phone }}</td>
                        </tr>
                        <tr>
                            <th>Message</th>
                            <td>{{ reservation[0].message }}</td>
                        </tr>
                        <tr>
                            <th>Status</th>
                            <td>{{ reservation[0].status }}</td>
                        </tr>
                        <tr>
                            <th>Created_at</th>
                            <td>{{ reservation[0].created_at }}</td>
                        </tr>
                </table>
            </div>
        </div>
        <!--/.row-->
    </div>
    <!--/.container-->
</section>
<!--/#content-->

{% endblock %}

templates/user/reservations.html.twig
{% extends 'homebase.html.twig' %}

{% block title %}{{ app.user.name }}-Reservations{% endblock %}

{% block body %}
<section id="content" class="shortcode-item">
    <div class="container">
        <div class="row">
            <div class="col-xs-4 col-sm-2">

                <div class="tab-wrap">
                    <div align="center" class="media">
                        {{ include('user/usermenu.html.twig') }}

                        <!--/.media-body-->
                    </div>
                    <!--/.media-->
                </div>
                <!--/.tab-wrap-->
            </div>
            <!--/.col-sm-6-->

            <div align="center" class="col-xs-8 col-sm-10">
                <h2>My Rents</h2>

                <table class="table">
                    <thead>
                    <tr>
                        <th>Home</th>
                        <th>Name</th>
                        <th>Surname</th>
                        <th>Email</th>
                        <th>Phone</th>
                        <th>Message</th>
                        <th>Status</th>
                        <th>Created_at</th>
                        <th>actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for reservation in reservations %}
                        <tr>
                            <td><a href="{{ path('user_show', {'id': reservation.userid}) }}">{{ reservation.name }}</a></td>
                            <td><a href="{{ path('ev_show', {'id': reservation.evid}) }}">{{ reservation.hname }}</a></td>
                            <td>{{ reservation.surname }}</td>
                            <td>{{ reservation.email }}</td>
                            <td>{{ reservation.phone }}</td>
                           <!-- <td>{{ reservation.checkin ? reservation.checkin|date('Y-m-d H:i:s') : '' }}</td>
                            <td>{{ reservation.checkout ? reservation.checkout|date('Y-m-d H:i:s') : '' }}</td> -->
                            <td>{{ reservation.message }}</td>
                            <td>{{ reservation.status }}</td>
                            <td>{{ reservation.created_at }}</td>
                            <td>
                                <a href="{{ path('user_reservation_show', {'id': reservation.id}) }}">show</a>
                            </td>
                        </tr>
                    {% else %}
                        <tr>
                            <td colspan="18">no records found</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <!--/.row-->
    </div>
    <!--/.container-->
</section>
<!--/#content-->

{% endblock %}

templates/user/show.html.twig
{% extends 'homebase.html.twig' %}

{% block title %}{{ app.user.name }}-Profile{% endblock %}

{% block body %}
<section id="content" class="shortcode-item">
    <div class="container">
        <div class="row">
            <div class="col-xs-4 col-sm-2">

                <div class="tab-wrap">
                    <div align="center" class="media">
                        {{ include('user/usermenu.html.twig') }}

                        <!--/.media-body-->
                    </div>
                    <!--/.media-->
                </div>
                <!--/.tab-wrap-->
            </div>
            <!--/.col-sm-6-->

            <div align="center" class="col-xs-8 col-sm-10">

                <table class="table">
                    <tbody>
                        <tr>
                            <th>Id</th>
                            <td>{{ app.user.id }}</td>
                        </tr>
                        <tr>
                            <th>Email</th>
                            <td>{{ app.user.email }}</td>
                        </tr>
                        <tr>
                            <th>Roles</th>
                            <td>{{ app.user.roles ? app.user.roles|json_encode : '' }}</td>
                        </tr>
                        <tr>
                            <th>Password</th>
                            <td>{{ app.user.password }}</td>
                        </tr>
                        <tr>
                            <th>Name</th>
                            <td>{{ app.user.name }}</td>
                        </tr>
                        <tr>
                            <th>Surname</th>
                            <td>{{ app.user.surname }}</td>
                        </tr>
                        <tr>
                            <th>Image</th>
                            <td><img src="{{ asset ('uploads/images/' ~ app.user.image) }}" height="90"></td>
                        </tr>
                        <tr>
                            <th>Status</th>
                            <td>{{ app.user.status }}</td>
                        </tr>
                        <tr>
                            <th>Created_at</th>
                            <td>{{ app.user.createdAt ? app.user.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                        </tr>
                        <tr>
                            <th>Updated_at</th>
                            <td>{{ app.user.updatedAt ? app.user.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
                        </tr>
                    </tbody>
                </table>
                <a href="{{ path('user_edit', {'id': app.user.id}) }}"><button type="button"
                        class="btn btn-info">edit</button></a>

            </div>
        </div>
        <!--/.row-->
    </div>
    <!--/.container-->
</section>
<!--/#content-->

{% endblock %}